-- User test data
INSERT INTO USER (FIRSTNAME, LASTNAME, Status) VALUES ('John', 'Doe', true);
INSERT INTO USER (FIRSTNAME, LASTNAME) VALUES ('Max', 'Mustermann');
INSERT INTO USER (FIRSTNAME, LASTNAME) VALUES ('Mary', 'Jane');

-- other tables TODO

--Insert into ROLE table
INSERT INTO ROLE(ROLENAME) VALUES ('Admin');
INSERT INTO ROLE(ROLENAME) VALUES ('ProjectManager');
INSERT INTO ROLE(ROLENAME) VALUES ('TestManager');
INSERT INTO ROLE(ROLENAME) VALUES ('Developer');
INSERT INTO ROLE(ROLENAME) VALUES ('Tester');