-- User test data
INSERT INTO USER (FIRSTNAME, LASTNAME, Status, password, username) VALUES ('John', 'Doe', true,'pass','john.doe');
INSERT INTO USER (FIRSTNAME, LASTNAME, password, username) VALUES ('Max', 'Mustermann', 'pass','max.muster');
INSERT INTO USER (FIRSTNAME, LASTNAME) VALUES ('Mary', 'Jane');

-- other tables TODO

INSERT INTO PERMISSION (DESCRIPTION, PERMISSIONNAME) VALUES ('some descript text', 'PERMISSION_MANAGEMENT');
INSERT INTO PERMISSION (DESCRIPTION, PERMISSIONNAME) VALUES ('some other text', 'USER_MANAGEMENT');
INSERT INTO PERMISSION (DESCRIPTION, PERMISSIONNAME) VALUES ('some other text2222', 'BUG_MANAGEMENT');


INSERT INTO ROLE (ROLENAME) VALUES ('ADM');
INSERT INTO ROLE (ROLENAME) VALUES ('PM');
INSERT INTO ROLE (ROLENAME) VALUES ('TM');
INSERT INTO ROLE (ROLENAME) VALUES ('DEV');
INSERT INTO ROLE (ROLENAME) VALUES ('TEST');

INSERT INTO ROLE_PERMISSION (ID_ROLE, ID_PERMISSION) VALUES (1, 1);
INSERT INTO ROLE_PERMISSION (ID_ROLE, ID_PERMISSION) VALUES (1, 2);
INSERT INTO ROLE_PERMISSION (ID_ROLE, ID_PERMISSION) VALUES (2, 3);
INSERT INTO ROLE_PERMISSION (ID_ROLE, ID_PERMISSION) VALUES (2, 2);