-- User test data
INSERT INTO USER (FIRSTNAME, LASTNAME, USERNAME, PASSWORD, STATUS) VALUES ('John', 'Doe', 'johndoe', '1234', true);
INSERT INTO USER (FIRSTNAME, LASTNAME, STATUS) VALUES ('Max', 'Mustermann', false);
INSERT INTO USER (FIRSTNAME, LASTNAME) VALUES ('Mary', 'Jane');

-- other tables TODO